# Copyright 2024 Hewlett Packard Enterprise Development LP
name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  actions: read # permission to read other github actions
  contents: write # contents needed for compliance
  id-token: write # id-token needed for hpe-hcss/github-oidc-app. This authenticates the runner to AWS ECR.
  packages: read # packages needed to read the build container
  pull-requests: write # needed for compliance

concurrency:
  # Only allows one build per workflow & branch/PR/tag
  # cancels in-progress builds for that branch/PR/tag if a new one is submitted.
  # https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  tags:
    outputs:
      computed_tag: ${{ steps.generate_tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags for tag management

      - name: Generate Tag
        id: generate_tag
        run: |
          TAG_VERSION="v0.1.0-$(echo $GITHUB_SHA | cut -c1-7)"
          echo "tag=$TAG_VERSION" >> $GITHUB_ENV
          echo "::set-output name=tag::$TAG_VERSION"

  package:
    needs:
      - tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Package common chart with version
        env:
          VERSION: ${{ needs.tags.outputs.computed_tag }}
        run: make package-common VERSION=$VERSION
      - name: Build dependencies for job example
        run: make update-deps-job
      - name: Validate job example
        run: make template-job
      - name: Build dependencies for service example
        run: make update-deps-service
      - name: Validate service example
        run: make template-service
      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-charts
          path: ./charts/*.tgz