name: Validate Quality Indicators

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-service-quality-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Service Quality JSON
      # Uses the main branch of the github action repository
      # This will fail if the JSON file is not kept up to date with the latest definitions
      # Definitions are kept in the hpe-cds/quality-chapter repository
      # https://github.com/hpe-cds/quality-chapter/blob/main/.github/actions/common/qualityIndicatorsDefinitions.json
      uses: hpe-cds/quality-chapter/.github/actions/validate-service-quality@main
      with:
        json-file: 'quality-indicators/ssoBrokerQualityIndicators.json'
